%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

on:
  push:
    branches:
      - 'experimental'
      - 'latest'
      - 'master'
      - 'stable'
      - 'staging'

env:
  GHCIU_STEPSUMM_RELEASE_TAG: 'auto-ci-release/${{ github.ref_name }}'


jobs:
  job_ci_test:
    runs-on: ubuntu-latest
    name: 'CI tests (usually â‰¤ 3 min)'
    steps:
      - uses: actions/checkout@v4
      - uses: mk-pmb/github-ci-util-2405-pmb/act/install@experimental
      - run: ghciu './test/ci.sh'

      - name: 'Publish auto-release'
        if: always()
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          artifactErrorsFailBuild: True
          artifacts: 'dist/*'
          body: '&nbsp;' # If empty, GitHub would use the commit message.
          makeLatest: False
          prerelease: True
          removeArtifacts: True # Remove old files from release.
          commit: '${{ github.sha }}'
          tag: '${{ env.GHCIU_STEPSUMM_RELEASE_TAG }}'

...
